package namod.j2me.network;

import android.graphics.Bitmap;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.Locale;

import javax.microedition.lcdui.Image;

public class TabStatusManager {
	public static class TabStatus {
		public final int tabIndex;
		public final String tabName;
		public final boolean isRunning;
		public final boolean isOnline;
		public final boolean wasConnected;
		public final long uptimeMs;
		public final long bytesIn;
		public final long bytesOut;
		public final long ramUsedMB;

		public TabStatus(int tabIndex, String tabName, boolean isRunning, boolean isOnline,
						 boolean wasConnected, long uptimeMs, long bytesIn, long bytesOut, long ramUsedMB) {
			this.tabIndex = tabIndex;
			this.tabName = tabName;
			this.isRunning = isRunning;
			this.isOnline = isOnline;
			this.wasConnected = wasConnected;
			this.uptimeMs = uptimeMs;
			this.bytesIn = bytesIn;
			this.bytesOut = bytesOut;
			this.ramUsedMB = ramUsedMB;
		}
	}

	public static boolean isTabMenu(String listTitle, String itemTitle) {
		if (listTitle != null) {
			String lower = listTitle.toLowerCase(Locale.ROOT);
			if (lower.contains("angelchip") || lower.contains("tab") || lower.contains("menu tab") || lower.contains("chọn tab")) {
				return true;
			}
		}
		if (itemTitle != null) {
			String trimmed = itemTitle.trim();
			if (trimmed.matches("\\d+") || trimmed.toLowerCase(Locale.ROOT).startsWith("tab ")) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Checks whether the item's icon contains the green play triangle overlay
	 * generated by MidletInfo.runimg (-16711936 / 0xFF00FF00) in the bottom-right quadrant.
	 */
	public static boolean isIconMarkedRunning(Image image) {
		if (image == null) return false;
		Bitmap bmp = image.getBitmap();
		if (bmp == null) return false;
		int w = bmp.getWidth();
		int h = bmp.getHeight();
		if (w < 10 || h < 10) return false;

		int startX = Math.max(0, w - (w / 3) - 2);
		int startY = Math.max(0, h - (h / 3) - 2);
		for (int y = startY; y < h; y++) {
			for (int x = startX; x < w; x++) {
				int pixel = bmp.getPixel(x, y);
				if (pixel == -16711936 || (pixel & 0x00FFFFFF) == 0x0000FF00) {
					return true;
				}
			}
		}
		return false;
	}

	public static boolean isTabThreadActive(int tabIndex) {
		String pkgPrefix = "package" + (tabIndex + 1) + ".";
		try {
			for (Thread t : Thread.getAllStackTraces().keySet()) {
				if (t.isAlive()) {
					StackTraceElement[] st = t.getStackTrace();
					for (StackTraceElement elem : st) {
						if (elem.getClassName().contains(pkgPrefix)) {
							return true;
						}
					}
				}
			}
		} catch (Throwable ignored) {
		}
		return false;
	}

	private static boolean checkMrQuyetReflection(int tabIndex) {
		try {
			ClassLoader cl = Thread.currentThread().getContextClassLoader();
			Class<?> mrQuyetClass = null;
			try {
				mrQuyetClass = Class.forName("MrQuyet.MrQuyet", true, cl);
			} catch (Throwable e1) {
				try {
					mrQuyetClass = Class.forName("MrQuyet.MrQuyet");
				} catch (Throwable ignored) {
				}
			}
			if (mrQuyetClass != null) {
				for (Field f : mrQuyetClass.getDeclaredFields()) {
					if (Modifier.isStatic(f.getModifiers()) && f.getType().isArray()) {
						f.setAccessible(true);
						Object val = f.get(null);
						if (val instanceof Object[]) {
							Object[] arr = (Object[]) val;
							if (tabIndex >= 0 && tabIndex < arr.length && arr[tabIndex] != null) {
								return true;
							}
						}
					}
				}
			}
		} catch (Throwable ignored) {
		}
		return false;
	}

	public static TabStatus getStatus(int tabIndex, String name, Image iconImage) {
		boolean isRunning = false;

		// 1. Direct icon analysis (100% accurate with MrQuyet's runimg green play marker)
		if (isIconMarkedRunning(iconImage)) {
			isRunning = true;
		}

		// 2. Reflection check on MIDlet array
		if (!isRunning && checkMrQuyetReflection(tabIndex)) {
			isRunning = true;
		}

		// 3. Active thread scan
		if (!isRunning && isTabThreadActive(tabIndex)) {
			isRunning = true;
		}

		// 4. Socket check
		NetworkTracker.SocketInfo socketInfo = NetworkTracker.getSocketInfoForTab(tabIndex);
		boolean isOnline = socketInfo != null && socketInfo.isOnline();
		boolean wasConnected = socketInfo != null && (socketInfo.bytesRead.get() > 0 || socketInfo.bytesWritten.get() > 0);
		if (isOnline || wasConnected) {
			isRunning = true;
		}

		long uptimeMs = 0;
		long bytesIn = 0;
		long bytesOut = 0;
		if (socketInfo != null) {
			if (isOnline) {
				uptimeMs = System.currentTimeMillis() - socketInfo.connectTime;
			}
			bytesIn = socketInfo.bytesRead.get();
			bytesOut = socketInfo.bytesWritten.get();
		}

		// RAM calculation
		Runtime rt = Runtime.getRuntime();
		long usedBytes = rt.totalMemory() - rt.freeMemory();
		long totalUsedMB = Math.max(1, usedBytes / (1024 * 1024));

		int runningTabs = getRunningTabCount();
		long tabRamMB = isRunning ? Math.max(16, totalUsedMB / Math.max(1, runningTabs)) : 0;

		return new TabStatus(tabIndex, name, isRunning, isOnline, wasConnected, uptimeMs, bytesIn, bytesOut, tabRamMB);
	}

	public static int getRunningTabCount() {
		try {
			ClassLoader cl = Thread.currentThread().getContextClassLoader();
			Class<?> mrQuyetClass = null;
			try {
				mrQuyetClass = Class.forName("MrQuyet.MrQuyet", true, cl);
			} catch (Throwable e1) {
				try {
					mrQuyetClass = Class.forName("MrQuyet.MrQuyet");
				} catch (Throwable ignored) {
				}
			}
			if (mrQuyetClass != null) {
				for (Field f : mrQuyetClass.getDeclaredFields()) {
					if (Modifier.isStatic(f.getModifiers()) && f.getType().isArray()) {
						f.setAccessible(true);
						Object val = f.get(null);
						if (val instanceof Object[]) {
							Object[] arr = (Object[]) val;
							int count = 0;
							for (Object o : arr) {
								if (o != null) count++;
							}
							if (count > 0) return count;
						}
					}
				}
			}
		} catch (Throwable ignored) {
		}
		return Math.max(NetworkTracker.getActiveSocketCount(), 1);
	}

	public static String formatDuration(long ms) {
		if (ms <= 0) return "00:00";
		long totalSeconds = ms / 1000;
		long hours = totalSeconds / 3600;
		long minutes = (totalSeconds % 3600) / 60;
		long seconds = totalSeconds % 60;
		if (hours > 0) {
			return String.format(Locale.US, "%02dh%02dm%02ds", hours, minutes, seconds);
		} else {
			return String.format(Locale.US, "%02dm%02ds", minutes, seconds);
		}
	}

	public static String formatBytes(long bytes) {
		if (bytes <= 0) return "0K";
		if (bytes < 1024 * 1024) {
			return String.format(Locale.US, "%.1fK", bytes / 1024.0f);
		} else {
			return String.format(Locale.US, "%.1fM", bytes / (1024.0f * 1024.0f));
		}
	}
}
