Manifest-Version: 1.0
MIDlet-1: NinjaNamod,/icon.png,GameMidlet
MIDlet-Vendor: NinjaNamod
MIDlet-Version: 1.4.8
MIDlet-Name: NinjaNamod
MicroEdition-Configuration: CLDC-1.1
MicroEdition-Profile: MIDP-2.1
Created-By: 25.0.3 (Ubuntu)

